In [196]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [197]:
df = pd.read_csv('/content/drive/MyDrive/ML Projects/Project_2_Loan_Approval/loan_approval.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [198]:
df.shape # It give info about Total entries,Columns
df.info() # It gives info Columns name , NaN values quantity, data type.
df.describe() # it gives info about only Numerical columns and mean,median,min,max,std

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [199]:
df.isnull().sum() # it gives info about how much null values in which column with adding all NaN with .sum() .

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [200]:
df["Gender"].mode()

0    Male
Name: Gender, dtype: object

In [201]:
df["Gender"].mode()[0]

'Male'

In [202]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])# Its a Categorical column so fillna with Mode.

df["Gender"].isnull().sum()

np.int64(0)

In [203]:
df["Married"] = df["Married"].fillna(df["Married"].mode()[0])# Its a Categorical column so fillna with Mode.
df["Married"].isnull().sum()

np.int64(0)

In [204]:
df["Dependents"] = df["Dependents"].fillna(df["Dependents"].mode()[0])# Its a Categorical column so fillna with Mode.
df["Dependents"].isnull().sum()

np.int64(0)

In [205]:
df["Self_Employed"] = df["Self_Employed"].fillna(df["Self_Employed"].mode()[0])# Its a Categorical column so fillna with Mode.
df["Self_Employed"].isnull().sum()

np.int64(0)

In [206]:
df["LoanAmount"].median()

128.0

In [207]:
df["LoanAmount"] = df["LoanAmount"].fillna(df["LoanAmount"].median()) # Fill NaN with the median for numerical column.

In [208]:
df["LoanAmount"].isnull().sum()

np.int64(0)

In [209]:
df["Loan_Amount_Term"] = df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].mode()[0])# Its a Categorical column so fillna with Mode.
df["Loan_Amount_Term"].isnull().sum()

np.int64(0)

In [210]:
df["Credit_History"] = df["Credit_History"].fillna(df["Credit_History"].mode()[0])# Its a Categorical column so fillna with Mode.
df["Credit_History"].isnull().sum()

np.int64(0)

In [211]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [212]:
df.duplicated().sum()

np.int64(0)

In [213]:
df = df.drop("Loan_ID",axis=1) # Removing Loan_ID Column.

df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [214]:
df["Dependents"].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [215]:
df["Dependents"] = df["Dependents"].replace("3+", "3")

In [216]:
df["Dependents"] = df["Dependents"].astype(int)

In [217]:
df["Dependents"].dtype

dtype('int64')

In [218]:
df["Gender"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})

In [219]:
df["Gender"].head()

0    1
1    1
2    1
3    1
4    1
Name: Gender, dtype: int64

In [220]:
df["Gender"].dtype

dtype('int64')

In [221]:
df["Married"] = df["Married"].map({"Yes": 1, "No": 0})

In [222]:
df["Married"].head()

0    0
1    1
2    1
3    1
4    0
Name: Married, dtype: int64

In [223]:
df["Married"].dtype

dtype('int64')

In [224]:
df["Education"] = df["Education"].map({"Graduate": 1, "Not Graduate": 0})

In [225]:
df["Education"].head()

0    1
1    1
2    1
3    0
4    1
Name: Education, dtype: int64

In [226]:
df["Education"].dtype

dtype('int64')

In [227]:
df["Self_Employed"] = df["Self_Employed"].map({"Yes": 1, "No": 0})

In [228]:
df["Self_Employed"].head()

0    0
1    0
2    1
3    0
4    0
Name: Self_Employed, dtype: int64

In [229]:
df["Self_Employed"].dtype

dtype('int64')

In [230]:
df["Loan_Status"] = df["Loan_Status"].map({"Y": 1, "N": 0})

In [231]:
df["Loan_Status"].head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

In [232]:
df["Loan_Status"].dtype

dtype('int64')

In [233]:
df = pd.get_dummies(df,columns=["Property_Area"], drop_first=True,dtype=int) # To convert Categorical data into One-Hot-Encoding.

In [234]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0.0,128.0,360.0,1.0,1,0,1
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,0,1

In [235]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Loan_Status',
       'Property_Area_Semiurban', 'Property_Area_Urban'],
      dtype='object')

In [236]:
x = df.drop("Loan_Status",axis=1)
y = df["Loan_Status"]

In [237]:
x.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0.0,128.0,360.0,1.0,0,1
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,0,1

In [238]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

In [239]:
x.shape

(614, 12)

In [240]:
y.shape

(614,)

In [241]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [242]:
x_train.shape

(491, 12)

In [243]:
x_test.shape

(123, 12)

In [244]:
y_train.shape

(491,)

In [245]:
y_test.shape

(123,)

In [246]:
# feature scaling to resolve(ConvergenceWarning:
#lbfgs failed to converge (status=1):STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [247]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train, y_train)

LogisticRegression()

In [248]:
y_pred = model.predict(x_test)

In [249]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [250]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

0.7886178861788617

In [251]:
# Confusion Matrix,Precision, Recall aur F1 Score(TP, TN, FP, FN).
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[18 25]
 [ 1 79]]

In [252]:
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)

print(precision)

0.7596153846153846

In [253]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred)

print(f1)

0.8586956521739131

In [254]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.42      0.58        43
           1       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123

In [255]:
import joblib

joblib.dump(model, "/content/drive/MyDrive/ML Projects/Project_2_Loan_Approval/model.pkl")
joblib.dump(scaler, "/content/drive/MyDrive/ML Projects/Project_2_Loan_Approval/scaler.pkl")

['/content/drive/MyDrive/ML Projects/Project_2_Loan_Approval/scaler.pkl']

In [259]:
import os

os.listdir()

['.config',
 'Loan_Approval_Model.pkl',
 'drive',
 'Loan_Approval_Scaler.pkl',
 'sample_data']